### ISSUE TITLE
XM530 camera not detected

### ISSUE THREAD

**Issue by ElVasquito** [NeiroNx/python-dvr#17]
Hello!

Currently I have this XM530 camera on an isolated WiFi with no net connection. Board says: COB-ETH-S V2.01 - IPC-RM1-BLK530AI-2003
I would like to get this repo working, to change the gateway so I can connect it to my main Wifi and it won't connect to the "P2P cloud" etc, and use it with RTSP only, and maybe change other settings of the camera like OSD and such. I won't install the official ActiveX Plugin as the executables are scrambled and Xiaongmai doesn't seem to have a good reputation of trust, so I don't know what it would install on the PC when using it.
So far, DeviceManager.py detects the camera successfully and shows some data, but it won't do much else.
connect.py will not connect at all, it would simply timeout or sometimes just show this:
'''
C:\Python37\python-dvr-master>python connect.py
Traceback (most recent call last):
  File "connect.py", line 14, in <module>
    if cam.login():
  File "C:\Python37\python-dvr-master\dvrip.py", line 166, in login
    self.alive_time = data["AliveInterval"]
KeyError: 'AliveInterval'
'''
Attaching screenshot.
Any clues on how to get it running? TIA
![XM530](https://user-images.githubusercontent.com/55246603/106089805-817c3b80-6107-11eb-9ace-c78b2405d401.jpg)

**Comment by NeiroNx** [comment]
It sends unusual answer... 
try change line 166 to
```python
self.alive_time = data["AliveInterval"] if "AliveInterval" in data else 10
```

**Comment by ElVasquito** [comment]
Thank you, that made some progress on connect, however, after a few seconds this exception pops up:
'''
Success! Connected to 192.168.137.144
{"OSDInfo": [{"Info": ["Тест00", "Test01", "Test02"], "OSDInfoWidget": {"BackColor": "0x40000000","EncodeBlend": true, "FrontColor": "0xF0FFFFFF", "PreviewBlend": true, "RelativePos": [6144, 6144,8192, 8192]}}], "strEnc": "UTF-8"}
unpack requires a buffer of 20 bytes
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python37x64\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Python37x64\lib\threading.py", line 1158, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Python37\python-dvr-master\dvrip.py", line 389, in keep_alive
    {"Name": "KeepAlive", "SessionID": "0x%08X" % self.session},
  File "C:\Python37\python-dvr-master\dvrip.py", line 126, in send
    payload,
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
'''
So it seems it can't KeepAlive for some reason, suspecting many commands were removed.
