### ISSUE TITLE
Cannot change IP address via Device Manager - KeyError: 'MaxBps'

### ISSUE THREAD

**Issue by SYPark0795** [NeiroNx/python-dvr#39]
Camera model is IVG-85HG50PYA-S

Following is the console log
```
$ python3 -m DeviceManager 
Search
timed out
Searching XM, found 1 devices

Vendor	MAC Address		Name	IP Address	Port
xm	00:12:15:86:aa:80	LocalHost	192.168.1.15	34567

{
    "Brand": "xm",
    "BuildDate": "2020- 9- 1 14:38:48",
    "ChannelNum": 1,
    "DeviceType": 0,
    "GateWay": "0x0101A8C0",
    "HostIP": "0x0F01A8C0",
    "HostName": "LocalHost",
    "HttpPort": 80,
    "MAC": "00:12:15:86:aa:80",
    "MonMode": "TCP",
    "NetConnectState": 0,
    "OtherFunction": "D=2022-09-21 16:30:37 V=b4522bf2ea14eb6",
    "SN": "718ca897556251c6",
    "SSLPort": 8443,
    "Submask": "0x0000FFFF",
    "TCPMaxConn": 10,
    "TCPPort": 34567,
    "UDPPort": 34568,
    "UseHSDownLoad": false,
    "Version": "V5.00.R02.000529B2.10010.040600.0020000"
}
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/mintpark/2022/FIRMWARE/1018 python-dvr/venv/lib/python3.8/site-packages/DeviceManager.py", line 1036, in setconfig
    result = ProcessCMD(
  File "/home/mintpark/2022/FIRMWARE/1018 python-dvr/venv/lib/python3.8/site-packages/DeviceManager.py", line 810, in ProcessCMD
    return configure[devices[cmd[1]]["Brand"]](cmd)
  File "/home/mintpark/2022/FIRMWARE/1018 python-dvr/venv/lib/python3.8/site-packages/DeviceManager.py", line 448, in ConfigXM
    config[u"MaxBps"] = devices[data[1]][u"MaxBps"]
KeyError: 'MaxBps'
```

It seems like 'TransferPlan' is missing in the JSON dump as well, compared to `ConfigXM` contents.

**Comment by SYPark0795** [comment]
I have tried commenting out "MaxBps" and "TransferPlan" in the ConfigXM function, and then I have found `sofia_hash` has additional `self` parameter. After deleting it, I was able to change the IP address.

**Comment by SYPark0795** [comment]
Thanks for the quick action. It still seems like `sofia_hash` has `self` parameter, while it is not a class method
