### ISSUE TITLE
Cannot connect to camera

### ISSUE THREAD

**Issue by snepedz** [NeiroNx/python-dvr#54]
the dvr is dahua PC-NVR-V3.0

from dvrip import DVRIPCam
from time import sleep

host_ip = '192.168.1.51'

cam = DVRIPCam(host_ip, user='admin', password='admin')
if cam.login():
	print("Success! Connected to " + host_ip)
else:
	print("Failure. Could not connect.")

i run the python 
python main-DVR-IP.py

this is the terminal output :

Traceback (most recent call last):
  File "/home/pc/.local/lib/python3.11/site-packages/dvrip.py", line 115, in connect
    self.socket.connect((self.ip, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/pc/main-DVR-IP.py", line 7, in <module>
    if cam.login():
       ^^^^^^^^^^^
  File "/home/pc/.local/lib/python3.11/site-packages/dvrip.py", line 228, in login
    self.connect()
  File "/home/pc/.local/lib/python3.11/site-packages/dvrip.py", line 127, in connect
    raise SomethingIsWrongWithCamera('Cannot connect to camera')
dvrip.SomethingIsWrongWithCamera: Cannot connect to camera

**Comment by widgetii** [comment]
I don't see Dahua in the list of supported vendors
